### ISSUE TITLE
Installing async_button warning -> adafruit_asyncio is not a known package

### ISSUE THREAD

**Issue by javigit** [furbrain/CircuitPython_async_button#1]
I believe the correct package name is **_asyncio_** instead of **_adafruit_asyncio_**, which I found here https://github.com/adafruit/Adafruit_CircuitPython_asyncio
-- circup install asyncio 

![2023-04-24_12-13](https://user-images.githubusercontent.com/12707286/234055334-1d673ecd-b7bd-4d77-b9a3-8a1d36fe5c3b.png)

**Comment by furbrain** [comment]
This is actually a bug in `circup`. I have created a pull request (https://github.com/adafruit/circup/pull/167) to fix it. I am therefore closing this issue - please reopen if this behaviour continues with an updated version of circup
