### ISSUE TITLE
Returning multiple results for "single" action

### ISSUE THREAD

**Issue by Foxxat** [furbrain/CircuitPython_async_button#2]
I'm not sure if this is lack of understanding how this library should handle single, double and triple presses.

I am dropping back to using examples/async_button_test.py to make the test as simple as possible using a Pico W with CircuitPython V8.

When I double click on a button it returns both Single Click and Double Click in the results.
For triple click it returns Single Click, Double Click and Triple Click.

e.g. for a triple click - only pressing the button 3 times I get

COUNTER: 22
COUNTER: 23
Single click seen
Double click seen
Triple click seen
COUNTER: 24
COUNTER: 25

Is this as designed and the user is supposed to handle this or should it only be returning one result ?

Thanks - it's a great library :)

**Comment by furbrain** [comment]
Hi, this behaviour is as expected. Using wait_for_click will return on any type of click.
If you just want to wait for a double click, use
```await my_button.wait(Button.DOUBLE)```
